"""The fixed, platform-wide permission catalog. Tenants cannot add to this
list — they can only decide which of these each of their roles grants."""

PERMISSION_CATALOG: list[dict] = [
    {"code": "loans.create", "module": "loans", "description": "Submit a new loan request"},
    {"code": "loans.approve", "module": "loans", "description": "Approve or reject submitted loan requests"},
    {"code": "loans.edit_rate", "module": "loans", "description": "Edit a loan's interest rate after creation"},
    {"code": "loans.view", "module": "loans", "description": "View loans"},
    {"code": "loans.lifecycle", "module": "loans", "description": "Record prepayment, restructuring, or write-off"},
    {"code": "payments.record", "module": "payments", "description": "Record a payment against an installment"},
    {"code": "clients.create", "module": "clients", "description": "Create a client"},
    {"code": "clients.edit", "module": "clients", "description": "Edit a client, including name changes"},
    {"code": "clients.delete", "module": "clients", "description": "Soft-delete a client"},
    {"code": "clients.view", "module": "clients", "description": "View clients"},
    {"code": "products.manage", "module": "products", "description": "Create, edit, or remove products"},
    {"code": "products.view", "module": "products", "description": "View products"},
    {"code": "roles.manage", "module": "users", "description": "Create roles and assign permissions"},
    {"code": "users.manage", "module": "users", "description": "Invite, edit, or deactivate users"},
    {"code": "settings.manage", "module": "settings", "description": "Manage tenant settings"},
    {"code": "activity_log.view", "module": "reports", "description": "View the activity log"},
    {"code": "reports.view", "module": "reports", "description": "View and export reports"},
    {"code": "dashboard.view", "module": "reports", "description": "View dashboard analytics"},

    # --- New Modules Added to Permission Set ---
    {"code": "branches.view", "module": "branches", "description": "View provincial branches and network coverage"},
    {"code": "branches.manage", "module": "branches", "description": "Create, edit, or delete branches and cash drawer limits"},
    {"code": "calculator.view", "module": "calculator", "description": "Access loan calculator and amortization schedule generator"},
    {"code": "field_collection.view", "module": "field_collection", "description": "View field collection sheets and borrower rosters"},
    {"code": "field_collection.manage", "module": "field_collection", "description": "Record field collections and issue mobile receipts"},
    {"code": "eod.view", "module": "eod", "description": "View End-of-Day batch processing status and logs"},
    {"code": "eod.run", "module": "eod", "description": "Execute manual End-of-Day closing batch and penalty accruals"},
    {"code": "watchlist.view", "module": "watchlist", "description": "View risk watchlist and loan stacking alerts"},
    {"code": "watchlist.manage", "module": "watchlist", "description": "Add or remove borrowers from the internal risk watchlist"},
    {"code": "cbc.view", "module": "cbc", "description": "Access Credit Bureau Cambodia (CBC) center and history"},
    {"code": "cbc.export", "module": "cbc", "description": "Generate and download monthly CBC regulatory data extracts"},
    {"code": "ews.view", "module": "early_warning", "description": "View early warning risk indicators and default predictions"},
    {"code": "documents.view", "module": "documents", "description": "View archived borrower KYC documents and contracts in vault"},
    {"code": "documents.upload", "module": "documents", "description": "Upload and archive borrower documentation in digital vault"},
    {"code": "collaterals.view", "module": "collaterals", "description": "View pledged collateral inventory and custody locations"},
    {"code": "collaterals.manage", "module": "collaterals", "description": "Update collateral custody locations and issue release certificates"},
    {"code": "guarantors.view", "module": "guarantors", "description": "View guarantor registry and cross-guarantee exposure matrix"},
    {"code": "reminders.view", "module": "reminders", "description": "View scheduled repayment reminders and alert templates"},
    {"code": "reminders.manage", "module": "reminders", "description": "Send manual SMS and Telegram payment reminder notices"},
    {"code": "officers.view", "module": "officers", "description": "View credit officer portfolio analytics and performance metrics"},
    {"code": "cashier.view", "module": "cashier", "description": "View cashier reconciliation records and closing drawers"},
    {"code": "cashier.reconcile", "module": "cashier", "description": "Perform cashier drawer count closing and sign vouchers"},
    {"code": "restructure.view", "module": "restructure", "description": "Simulate loan restructuring and debt workout scenarios"},
    {"code": "restructure.manage", "module": "restructure", "description": "Submit and approve formal loan restructuring proposals"},
    {"code": "nbc_provisioning.view", "module": "nbc_provisioning", "description": "View NBC loan loss provisioning matrix and reserve calculations"},
    {"code": "nbc_provisioning.export", "module": "nbc_provisioning", "description": "Export NBC prudential return reports and compliance statements"},
    {"code": "writeoffs.view", "module": "writeoffs", "description": "View written-off bad loans and recovery registers"},
    {"code": "writeoffs.manage", "module": "writeoffs", "description": "Submit and approve loan write-offs or record debt recovery"},
    {"code": "fx_exchange.view", "module": "fx_exchange", "description": "View dual-currency FX exchange drawer and transactions"},
    {"code": "fx_exchange.manage", "module": "fx_exchange", "description": "Execute currency conversions and adjust petty cash balance"},
    {"code": "telegram_bot.view", "module": "telegram_bot", "description": "View Telegram bot notification logs and scheduled briefings"},
    {"code": "telegram_bot.manage", "module": "telegram_bot", "description": "Configure Telegram bot tokens and trigger broadcast dispatches"},
    {"code": "leads.view", "module": "leads", "description": "View public online loan intake leads and pre-qualification requests"},
    {"code": "leads.manage", "module": "leads", "description": "Process, assign, and convert online loan leads into active loans"},
    {"code": "bakong.view", "module": "bakong", "description": "View Bakong KHQR real-time payment feed and reconciliation status"},
    {"code": "bakong.manage", "module": "bakong", "description": "Reconcile unmatched Bakong KHQR transactions and generate dynamic QR payways"},
    {"code": "scoring.view", "module": "scoring", "description": "View automated 5Cs credit scoring matrix and risk underwriting results"},
    {"code": "scoring.manage", "module": "scoring", "description": "Run credit underwriting evaluations and adjust risk scoring parameters"},
    {"code": "accounting.view", "module": "accounting", "description": "View General Ledger (GL) Chart of Accounts, Trial Balance, and financial statements"},
    {"code": "accounting.manage", "module": "accounting", "description": "Post manual journal vouchers and manage accounting periods"},
]
